name: golangci-lint
on:
  push:
    paths-ignore:
      - 'docs/**'
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1.2.1
        with:
          version: v1.27
